on:
  pull_request:
    types: [opened, synchronize, reopened]
name: Build Frontend
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        # not sure about node-version
        # with:
        #   node-version: '12.x'
      - name: Cache dependencies
        uses: actions/cache@v2
          # npm cache files are stored in `~/.npm` on Linux/macOS 
          # please see linked reference in PR request
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      #
      # CAUTION: These steps run on code in the the PR. They should not execute any code that might be included in the PR.
      # See: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions
      #
      - name: Install dependencies
        run: npm ci ## project docs say for contributors to run `npm install` should this reflect the docs? 
      - name: Checkout code format
        run: npm lint
      - name: Simulate production build
        run: npm run serve